### ISSUE TITLE
Revit Version?

### ISSUE THREAD

**Issue by heinrichboldt** [jeremytammik/UnitMigration#1]
Hi, 
found this and seems this is what I was searching, 

Does this Add-In working for Revit 2016/2017 and 2018? 
or is it only for higher branches? like 2020 and above?

**Comment by jeremytammik** [comment]
Look at the [list of releases](https://github.com/jeremytammik/UnitMigration/releases). Currently, only Revit 2020 is supported. You can also look at the date of the initial commit, 8 months ago, so in early 2020. If you require it for earlier releases of Revit, it should be pretty easy to back-port. Please fork this repository and submit a pull request for the changes you make, so that your modifications can easily be shared with others as well. Thank you!
